# Autochecks the repo, using formatting and linting commands we run on precommit JUUUUST to be sure
name: Autochecks
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  autocheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Each of these are commands we should run and check output
        command: ["lint", "lint:types", "format"]

    outputs:
      lint: ${{ steps.changes.outputs.lint }}
      lintstyles: ${{ steps.changes.outputs.lintstyles }}
      linttypes: ${{ steps.changes.outputs.linttypes }}
      format: ${{ steps.changes.outputs.format }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.2.2
      - run: pnpm install
        # Make sure types are generated before running the commmand
      # - run: pnpm db:generate
      - name: ${{ matrix.command }}
        run: pnpm ${{ matrix.command }}
      - name: Output changed files
        id: changes
        # Removes both leading/trailing whitespace after getting diffed files and removing package.json/pnpm.lock
        run: |
          CHANGED="$(git diff --name-only --diff-filter=ACMRT | xargs | sed 's/package.json//g;s/pnpm-lock.yaml//g;s/^[ \t]*//g;s/[ \t]*$//g')"
          COMMAND_NAME="${{ matrix.command }}"
          OUTPUTNAME="${COMMAND_NAME//:/}"
          echo "Changed files were: $CHANGED"
          echo "::set-output name=$OUTPUTNAME::$CHANGED"

  # If anything is output, fails this job!
  fail-on-diff:
    runs-on: ubuntu-latest
    needs: autocheck
    if: ${{ needs.autocheck.outputs.lint || needs.autocheck.outputs.linttypes || needs.autocheck.outputs.format }}
    steps:
      - name: Exiting because of changed files
        run: |
          echo "Changed from lint: ${{needs.autocheck.outputs.lint || 'none'}}"
          echo "Type check changed files: ${{needs.autocheck.outputs.linttypes || 'none'}}"
          echo "Files formatted: ${{needs.autocheck.outputs.format || 'none'}}"
          exit 1
